### ISSUE TITLE
Like Function

### ISSUE THREAD

**Issue by worakls90** [stanvanrooy/instauto#2]
Hi

`POST /api/v1/media/231529815458455678_174613709/like/

SIGNATURE
{
  "delivery_class": "organic",
  "media_id": "23154581568_174613709",
  "_csrftoken": "LGYsuPoltfgnjLLgT",
  "radio_type": "wifi-none",
  "_uid": "6780958545",
  "_uuid": "ghjuokt5-d78-d5tghjkihgde",
  "is_carousel_bumped_post": "false",
  "container_module": "feed_contextual_profile",
  "feed_position": "34"
}
{
  "d": "0"
}`

Are all parameters being sent ?

I think we missing feed_position.

**Comment by stanvanrooy** [comment]
feed_position is an optional parameter. It can be included in the request like this:

```python
like = PostLike.create(media_id="231545815679865678_174613709", feed_position="34")
client.post_like(like)
```

**Comment by worakls90** [comment]
Why do you say its an optional paramter ? I see it in every media like request.

Thank you for adding it to the docs.

**Comment by stanvanrooy** [comment]
Keep in mind that this project is currently in a very early alpha stage, and everything is subject to change. 

I'm trying to keep this library as flexible as possible, which means the user should be able to send the request with only the parameters required to get a 200 response, up until all parameters the app sends.

But, since most users would want to copy the behavior of the app, I assign the parameter a default value and the user will have to explicitely ignore it. For the feed_position param, I can't think of a good default value.
